Добавляет базовую стилизацию страницы с формой отзыва
htmlacademy-adaptive/520531-sedona-21 pull request #6
Opened 2020-11-25 19:44 UTC by pavelvorobev

2020-11-26 09:48 UTC, nikkypizza reviewed
В целом ок, но нужно поправить линтер.

Также ссылки в **main-nav__list** должны быть **uppercase**

-----

Если у тебя возникают вопросы - пиши их в комментарии к пр, разберемся со всем)

2020-11-26 09:48 UTC, nikkypizza commented on source/sass/blocks/feedback.scss
> +  }
для всех инпутов стиль шрифта плейсхолдера и самого инпута должны совпадать, у тебя они различаются. Также шрифт для textarea не подъехал.
![image](https://user-images.githubusercontent.com/30810655/100330229-c38de180-2fdf-11eb-8f9a-c936b3b8dfdd.png)

2020-11-26 09:48 UTC, nikkypizza commented on source/sass/blocks/page-main.scss
> +}
Тут и в некоторых других местах линтер спотыкается. Стоит прогонять команду `npm test` или `npm run stylelint` и вносить правки, пока не перестанет ругаться.

2020-11-26 09:48 UTC, nikkypizza commented on source/sass/blocks/feedback.scss
> +  line-height: 26px;
Все же сдавай сделаем миксин для этого https://github.com/htmlacademy-adaptive/520531-sedona-21/pull/5#discussion_r528324153

Одна из основных фич препроцессора - избавляться от дублирования кода. Настройка шрифта применяется почти для каждого блока, вполне резонно сделать для этого миксин

2020-11-26 09:48 UTC, nikkypizza commented on source/sass/blocks/feedback.scss
> +}
Ниже для стилизации плейсхолдера используется `&`

2020-11-26 16:44 UTC, pavelvorobev commented on source/sass/blocks/feedback.scss
> +  }
Почему-то font-family для .page не применился к плэйсхолдеру textarea, но для инпутов сработал как надо. Пропишу для textarea отдельно

2020-11-26 16:59 UTC, nikkypizza commented on source/sass/blocks/feedback.scss
> +  }
Вообще плейсхолдер же наследует стили от инпута. В нашем случае было бы достаточно лишь задать плейсхолдеру цвет текста чтобы он не выглядел серым, а все остальное прописать для инпута/textarea

2020-11-26 17:42 UTC, nikkypizza requested changes

2020-11-26 17:42 UTC, nikkypizza commented on source/sass/blocks/feedback.scss
> +    @include text-bold;
Плейсхолдер наследует стили от инпута. 
В нашем случае было бы достаточно лишь задать плейсхолдеру цвет текста чтобы он не выглядел серым, а все остальное прописать для самих инпутов/textarea

2020-11-26 17:42 UTC, nikkypizza commented on source/sass/blocks/page-main.scss
> +  @include text-bold;
Продублирую тут свой коммент из прошлого ПР https://github.com/htmlacademy-adaptive/520531-sedona-21/pull/5#discussion_r528324153

```scss
@mixin fontMeasure($weight, $size, $lineHeight) {
  font-weight: $weight;
  font-size: $size;
  line-height: $lineHeight;
}
//
@include fontMeasure(700, 18px, 26px);
```

https://sass-lang.com/documentation/at-rules/mixin#arguments

-----

Миксин должен принимать три агрумента - вес, размер, интерлиньяж. 

Текущий миксин `text-bold` не оч гибкий т.к. он всегда задает размер 18px/26px. В случае когда мы будем заниматься адаптацией нам придется завести еще с десяток таких миксинов, что лишает миксин смысла и только все усложняет.

Тут этот миксин бы использовался так: 
```css
@include fontMeasure(bold, 18px, 26px);
```

2020-11-26 17:42 UTC, nikkypizza commented on source/sass/blocks/feedback.scss
> +  font-family: "PT Sans", "Arial", sans-serif;
**font-family** также часто выносится в миксин для избегания опечаток, так как он часто пишется от руки во многих частях проекта

2020-11-28 14:44 UTC, nikkypizza approved these changes
![image](https://user-images.githubusercontent.com/30810655/93986466-0ee10500-fd8f-11ea-844f-6c07a2427b34.png)

2020-11-28 14:44 UTC, merged